import { add, multiply, rest, split } from './build'

console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')

// Suma dos números
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)

// Suma dos números
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)

multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)

split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
