console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')
console.log('build')

// Suma dos números
export function add(a: number, b: number): number {
  return a + b
}
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)
add(2, 2)

// Suma dos números
export function rest(a: number, b: number): number {
  return a - b
}

rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)
rest(3, 2)

// Suma dos números
export function multiply(a: number, b: number): number {
  return a * b
}

multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)
multiply(3, 2)

// Suma dos números
export function split(a: number, b: number): number {
  return a / b
}

split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
split(3, 2)
